### ISSUE TITLE
Cannot add Bag created files to Tagmanifest file in bagging version 4.0

### ISSUE THREAD

**Issue by Bolkun** [jscancella/bagging#41] opened 2020-07-22 11:54 UTC
## When submitting an issue please include:
* a small code example showing the incorrect behavior
BagBuilder builder = new BagBuilder();
		
builder.addAlgorithm("md5")
	.addMetadata("Bagging-Date", getCurrentISODate("yyyy-MM-dd")
        .addPayloadFile(ingestFolder)
        **.addTagFile(ingestFolder + "/bagit.txt")
        .addTagFile(ingestFolder + "/bag-info.txt")
        .addTagFile(ingestFolder + "/manifest-md5.txt")**
        .bagLocation(exportFolder)
	.write();

* the expected behavior
in tagmanifest-md5.txt
       eaa2c609ff6371712f623f5531945b44  bagit.txt
       063d7a5ee78b06a31a871dfd336ef6d1  bag-info.txt
       c30e579035a4f2b0fc38af0c43d31843  manifest-md5.txt

* the actual behavior
These code gives error: File not found exception.

* the operating system being used, and its version
debian 10

* version of Bagging being used
4.0

* If available Attach all logs, and or output, and or screenshots

## When submitting a feature request please include:
* Current behavior (if applicable)
* Proposed behavior
* Why this feature is useful
* A small code example if possible

## When submitting a question please:
* Please read the Frequently asked questions (FAQ) section of the [README](README.md) to see if your question has already been answered
* Use complete sentences to form your question

**Comment by jscancella** [comment] 2020-07-22 12:44
Hello @Bolkun and thank you for submitting an issue.
You do not need to manually add the tag files when creating a bag. See the example: https://github.com/jscancella/bagging#how-to-create-a-bag-programmatically

Also, please update to the latest version https://bintray.com/jscancella/com.github.jscancella/bagging/4.1

**Comment by Bolkun** [comment] 2020-07-22 12:59
@jscancella if I dont add these files, tagmanifest file will be empty. According to BagIt 1.0 specification Page7 "Each tag manifest MUST list every payload manifest." And this condition is not full filled. Did I missed smth.?

**Comment by jscancella** [comment] 2020-07-22 13:04
@Bolkun not sure what you are doing wrong, but if your statement was true this test would be failing but it isn't
https://github.com/jscancella/bagging/blob/master/src/test/java/com/github/jscancella/domain/BagTest.java#L45-L88

**Comment by Bolkun** [comment] 2020-07-22 13:20
I checked the test, but it checks only if manifest files exists. but not Assertions.assertEquals(
        Arrays.asList("xxxxxxxxxxxxxxxxxxxxxxxxxxxxx  manifest-md5.txt"), Files.readAllLines(expectedTagmanifestFile));

**Comment by jscancella** [comment] 2020-07-22 13:22
Not sure what you mean, it checks the contents of the manifest file on this line
https://github.com/jscancella/bagging/blob/master/src/test/java/com/github/jscancella/domain/BagTest.java#L81-L82

**Comment by Bolkun** [comment] 2020-07-22 13:32
The only test I can see is following
**Assertions.assertEquals(
        Arrays.asList("b1946ac92492d2347c6235b4d2611184  foo.txt"), Files.readAllLines(expectedTagmanifestFile));**
but it does not test this acording to spesification:
**Assertions.assertEquals(
        Arrays.asList("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  _manifest-md5.txt_"), Files.readAllLines(expectedTagmanifestFile));**
As you can see foo file already physical already exist somewhere, but manifest-md5.txt must be first created to be able to add it in tagmanifest-md5.txt file.

**Comment by jscancella** [comment] 2020-07-22 13:34
Ok I think I understand now. I believe the problem is here https://github.com/jscancella/bagging/blob/master/src/main/java/com/github/jscancella/domain/Bag.java#L338-L341
I don't have time to work on this right now, but feel free to submit a pull request.

**Comment by Bolkun** [comment] 2020-07-22 13:49
Thanks for taking time and care about this issue. I would have fix it, but I am not so experienced java developer, especially with unfamiliar projects.

**Comment by jscancella** [comment] 2020-07-23 00:08
please try version 4.2 which should fix your issue.

**Comment by Bolkun** [comment] 2020-07-23 08:21
@jscancella I tried 4.2 version and now manifest files are saved automaticaly, great job! But I have the same issue with **bagit.txt** and **bag-info.txt**. It would be great to have smth like this.

builder.addTagFile(ingestFolder + "/bagit.txt");  
builder.addTagFile(ingestFolder + "/bag-info.txt"); 

// bagit.txt and bag-info.txt are also physical not existing at a moment, before calling builder.write();

**Comment by jscancella** [comment] 2020-07-23 11:54
>  It would be great to have smth like this.
> builder.addTagFile(ingestFolder + "/bagit.txt");
> builder.addTagFile(ingestFolder + "/bag-info.txt");

I disagree, you shouldn't have to manually add those in, instead they should automatically be added to the tag files. When I get a chance I will update and fix this.

**Comment by Bolkun** [comment] 2020-07-23 15:17
I am also ok with a fact, when it would automatically be added to the tag files.

**Comment by jscancella** [comment] 2020-07-23 20:06
The fix will be in the next release.

**Closed by jscancella** 2020-07-23 20:06 UTC
Labels: bug
